##异常

###分类

异常对象都是派生于`Throwable`类，有两个分支
`Error`与`Exception`

程序错误导致的异常属于`RuntimeEcception`

###方法声明可能会抛出的异常

1. 调用一个抛出异常的方法，如FileInputStream
2. 程序运行中用throw抛出已检查异常
3. 程序出现错误
4. Java虚拟机和运行库出现的内部异常

```
class MyAnimation
{
	...
	public Image loadImage(String s) throws IOException, EOFExecption
	{
		...
		throw new EOFException();
	}
}
```

###自定义异常

```
class FileFormatException extends IOException
{
	public FileFormatException(){

	}

	public FIleFormatException(String gripe)
	{
		super(gripe);
	}
}
```

###捕获异常

```
try
{
	code...
}
catch (ExceptionType1 e)
{
	...
}
catch (ExceptionType2 e)
{
	//异常链
	Throwable se = new xxxException("xxx");
	se.initCause(e);	//用Throwable e = se.getCause();重新得到原始异常
	throw se;
}
```

###Finally子句

需要关闭资源时

执行条件:

1. 代码没有抛出异常
2. 代码抛出异常被catch捕获
3. 没有捕获到异常

```
try
{
	code...
}
catch (ExceptionType1 e)
{
	...
}
catch (ExceptionType2 e)
{
	//异常链
	Throwable se = new xxxException("xxx");
	se.initCause(e);	//用Throwable e = se.getCause();重新得到原始异常
	throw se;
}
finally
{
	//关闭资源
}
```

###堆栈跟踪元素

```
Throwable t = new Throwable();
StackTraceElement[] frames = t.getStackTrace();
for (StackTraceElement frame : frames)
{
	System.out.println(frame);
}
```

所有线程:

```
Map<Thread, StackTraceElement[]> map = Thread.getAllStackTraces();
for (Thread t : map.keySet())
{
	StackTraceElement[] frames = map.get(t);
	...
}
```

##断言

`assert 条件;` 如果结果有false,抛出一个AssertionError异常

`assert 条件 : 表达式;` 同上，表达式传入AssertionError


